apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/ryniu/git-ops-argocd-workshop.git
    targetRevision: main
    path: clusters/stage/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
