apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/ryniu/git-ops-argocd-workshop.git
    targetRevision: main
    path: apps/podinfo/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
