apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/ryniu/git-ops-argocd-workshop.git
    targetRevision: main
    path: apps/nginx-helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

